### ISSUE TITLE
train.npy and test.npy

### ISSUE THREAD

**Issue by lanchen2019** [gbouritsas/Neural3DMM#2]
What is train.npy and test.npy？How can I generate them?

**Comment by gerwang** [comment]
You need to obtain CoMA dataset from https://coma.is.tue.mpg.de/ and use its code to generate those npys.

**Comment by gbouritsas** [comment]
For any dataset: they are 3D tensors with dimensions: (number_meshes, number_vertices, input_dim). 
Basically, you stack all your training (or testing) meshes into a large tensor. We do that in order to compute the normalization constants (mean and standard deviation) that will be later applied to each mesh.
